version: '3.9'
  
services:
  redis_test:
    container_name: redis_test
    image: redis
    restart: always
    ports:
      - "6382:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend_test:
    build: .
    container_name: backend_test
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app_test/
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - redis_test


  worker_test:
    build: .
    command: celery -A core worker --loglevel warning
    volumes:
      - ./core:/app_test/
    depends_on:
      - redis_test
      - backend_test

    
