# Generated by Django 4.2.2 on 2024-02-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
