# Generated by Django 4.2.2 on 2024-02-14 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0004_comment_approach_comment_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="message",
            new_name="content",
        ),
    ]
