# Generated by Django 4.2.2 on 2024-02-22 13:26

import core.tools
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0008_post_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="create date"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="post/default.jpg",
                upload_to=core.tools.UploadToPathAndRename("posts"),
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AddField(
            model_name="post",
            name="modify_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="modify date"
            ),
        ),
        migrations.CreateModel(
            name="ImageFiled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="create date"
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="modify date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="post/default.jpg",
                        upload_to=core.tools.UploadToPathAndRename("posts"),
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="twitter.post"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
