# Generated by Django 4.2.2 on 2024-02-22 13:37

import core.tools
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0009_post_create_date_post_image_post_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefiled",
            name="image",
            field=models.ImageField(
                default="posts/default.jpg",
                upload_to=core.tools.UploadToPathAndRename("posts"),
            ),
        ),
    ]
