# Generated by Django 4.2.2 on 2024-02-22 13:38

import core.tools
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0010_alter_imagefiled_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="posts/default.jpg",
                upload_to=core.tools.UploadToPathAndRename("posts"),
            ),
        ),
    ]
