# Generated by Django 5.0.1 on 2024-04-01 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_remove_profile_email"),
        ("twitter", "0011_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_author",
                to="accounts.profile",
            ),
        ),
    ]
