# Generated by Django 4.2.2 on 2024-02-08 06:58

import core.tools
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AddField(
            model_name="profile",
            name="modify_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="modify date"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="twitter/default.jpg",
                upload_to=core.tools.UploadToPathAndRename("twitter"),
            ),
        ),
    ]
