# Generated by Django 4.2.2 on 2024-02-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_profile_is_active_profile_modify_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="descriptions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
