# Generated by Django 4.2.2 on 2024-02-11 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0007_alter_follow_follow_user_alter_follow_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="data",
            new_name="date",
        ),
        migrations.AlterField(
            model_name="follow",
            name="follow_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
