# Generated by Django 4.2.2 on 2024-02-12 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0008_rename_data_follow_date_alter_follow_follow_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_follow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
