# Generated by Django 4.2.2 on 2024-02-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_follow_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
