# Generated by Django 4.2.2 on 2024-02-16 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
