# Generated by Django 4.2.2 on 2024-02-16 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
