# Generated by Django 4.2.2 on 2024-02-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="follow_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_user",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_follow",
                to="accounts.profile",
            ),
        ),
    ]
