# Generated by Django 4.2.2 on 2024-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_alter_follow_follow_user_alter_follow_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
