# Generated by Django 5.0.1 on 2024-04-04 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_remove_profile_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user",
            new_name="username",
        ),
    ]
