# Generated by Django 5.0.1 on 2024-04-04 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_rename_user_profile_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="username",
            new_name="user",
        ),
    ]
