name: Docker Image for my Twitter Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker-Compose
        run: docker-compose -f docker-compose-stage.yml up --build
      - name: Run Tests
        run: docker exec backend_twitter sh -c "flake8 && pytest ."
