name: Docker Image for my Twitter Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Docker and Docker Compose
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '\"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and Start Containers
        run: docker-compose -f docker-compose-stage.yml up -d --build

      - name: Run Tests
        run: docker-compose -f docker-compose-stage.yml exec backend_twitter sh -c "flake8 && pytest ."

      - name: Shutdown Docker-Compose
        if: always()  # Ensure this step runs even if tests fail
        run: docker-compose -f docker-compose-stage.yml down
